version: '1.0'
services:
  - name: adminer
    type: docker
    image: adminer
    version: latest
    ports:
      - 8080
    remoteAccess: true
    deployTo:
      - adminer

hosts:
  - name: adminer
    requirements:
      cores: 1
      memory: 0.5
